directories:
  output: dist-malware-detection
  buildResources: build
appId: com.lamachineethique.malwaredetection
productName: La Machine Éthique - Détection de Malware
files:
  - filter:
      - main-malware-detection.js
      - malware-detection-interface.html
      - assets/**/*
      - node_modules/**/*
win:
  target: portable
  icon: assets/icon.ico
portable:
  artifactName: La-Machine-Ethique-Malware-Detection.exe
electronVersion: 36.4.0
